In [4]:
import numpy as np
from scipy.optimize import minimize

In [5]:
import pandas as pd
df = pd.read_excel(r"E:\code\meisai\source\2024\C\Wimbledon_featured_matches2(9).xlsx")

In [6]:
data = pd.read_csv(r"E:\code\meisai\source\2024\C\Wimbledon_featured_matches.csv", sep=',')
print(data.shape)
KK=df['K']
set_s=7 # H
game_s=9 #j
game_v=18 #S
set_v=19 #T
set_n=4 #E
game_n=5 #F
p_s=11 #L
server=13 #N
l=7283
p1_s=11
p2_s=12

(7284, 46)


In [7]:
def obj_fun(n):
    #n是[n1,n2,n3,n4]
    M=0
    Ra=130
    Rb=100
    for k in range(front,last):
        Ra=0.9*Ra+((n[0]**alpha_P1[k])*KK[k]-n[1]*beta_p1[k]-n[2]*omega_p1[k]+n[3]*z_p1[k])*gama_p1[k]
        Rb=0.9*Rb+((n[0]**alpha_p2[k])*KK[k]-n[1]*beta_p2[k]-n[2]*omega_p2[k]+n[3]*z_p2[k])*gama_p2[k]
        C=Ra-Rb
        M=M+((-1)**victor[k])*C*0.01+(Ra**2+Rb**2)*0.001
    return M

#n[0]对应是否发球,ELO
#n[1]对应失误
#n[2]对应体能消耗
#n[3]连胜

In [8]:
n_0 = np.array([5,5,5,5])
pd.set_option('display.float_format',lambda x : '%.5f' % x)

In [12]:
from scipy.optimize import Bounds

lb = [-5, -5, -5, -5]
ub = [15, 15, 15, 15]
bounds = Bounds(lb, ub)
i=0
p=np.zeros([1,4])
out=np.zeros([1,4])
num=0
while i < l:
    k=i
    while data.iloc[i,0]==data.iloc[k,0] and k<l:
        k=k+1
    front=i
    last=k-1
    i=k
    victor = df['point_victor'].iloc[df.index[front:last]]
    alpha_P1 = df['alpha_P1'].iloc[df.index[front:last]]
    alpha_p2 = df['alpha_p2'].iloc[df.index[front:last]]
    gama_p1 = df['(Sa-Ea)'].iloc[df.index[front:last]]
    gama_p2 = df['(Sb-Eb)'].iloc[df.index[front:last]]
    beta_p1 = df['beta_p1'].iloc[df.index[front:last]]
    beta_p2 = df['beta_p2'].iloc[df.index[front:last]]
    omega_p1 = df['omega_p1'].iloc[df.index[front:last]]
    omega_p2 = df['omega_p2'].iloc[df.index[front:last]]
    z_p1 = df['z_p1'].iloc[df.index[front:last]]
    z_p2 = df['z_p2'].iloc[df.index[front:last]]
    res= minimize(obj_fun, n_0, method='Powell')
    #out=np.append(out,res.x)
    print(res.x)
    num=num+1
    p=p+res.x

out=pd.DataFrame(out)
print(out)

[ 0.69880372 -0.53937356  0.00492759  1.03686186]
[ 0.83170528 -2.25393921  0.00246039  0.82891288]
[ 5.27392362e-01 -5.94739861e+00  1.61208936e-03  2.05328401e+00]
[0.73908504 0.14527231 0.00135333 0.35788286]
[7.12740381e-01 1.02161488e+00 8.83097106e-04 7.29286556e-01]
[8.23549564e-01 3.99922215e-01 7.24740169e-04 5.57678958e-01]
[ 8.62969996e-01 -1.20614596e+01  6.56586124e-04  1.26984320e+00]
[ 4.92105986e-01 -8.50414619e+00  4.61817719e-04  2.63675664e+00]
[ 8.26776998e-01 -7.28377153e+00  5.42578548e-04  1.74750104e+00]
[ 8.65520626e-01 -6.94415826e+00  5.62907365e-04  1.32533447e+00]
[ 1.30734540e+00 -6.34933211e+00  5.16454490e-04 -7.05490911e-01]
[ 1.17542143e+00 -1.34913721e+00  5.19615692e-04 -3.94045648e-01]
[ 1.01232631e+00  2.45114363e-01  3.91456436e-04 -7.32742317e-01]
[ 1.03070776e+00  4.59966798e+00  3.46610333e-04 -2.10602672e+00]
[7.21818268e-01 1.52230688e+00 2.59868592e-04 2.81845948e-01]
[ 1.09917868e+00  6.74042875e+00  2.86408629e-04 -2.71981263e+00]
[ 9.4631

In [13]:
print(p)
print(p.shape)
print(p/31)

[[ 2.60047311e+01 -5.14564776e+01  1.96355044e-02  1.10705503e+01]]
(1, 4)
[[ 8.38862293e-01 -1.65988637e+00  6.33403366e-04  3.57114525e-01]]
